### ISSUE TITLE
Getting some typescript error

### ISSUE THREAD

**Issue by Ridermansb** [chaance/vitest-dom#1]
![Screen Shot 2022-09-26 at 20 42 13](https://user-images.githubusercontent.com/725337/192399860-73ee69f8-24f9-4689-a13c-9011b152622c.png)

**Comment by chaance** [comment]
@Ridermansb Do you mind sharing a minimal repro I can look at? It's difficult to debug issues without the context of your code. I'll reopen the issue if so.

**Comment by SalahAdDin** [comment]
is this package still maintained?

**Comment by chaance** [comment]
Yes. If there's an issue here I can look into it with a minimal reproduction.
