### ISSUE TITLE
Bump vitest peerDependency

### ISSUE THREAD

**Issue by Kamahl19** [chaance/vitest-dom#2]
Currently it's `https://github.com/vitest-dev/vitest: "^0.16.0"` which fails when trying to install together with latest vitest 0.29.x

**Comment by oscaralanpierce** [comment]
It might be good to bump it to `"^0.16"` so it automatically accepts any 0.16 <= version < 1.0. It seems like Vitest updates pretty frequently - I just started using it a couple weeks ago and it's already gone up a minor version and two patch versions.

I'm not sure how much work will be involved in supporting later Vitest versions, but I'm happy to investigate and make a PR if it isn't too much work.

**Comment by themagickoala** [comment]
Created PR for this: https://github.com/chaance/vitest-dom/pull/3

**Comment by chaance** [comment]
Resolved in #3, I'll cut a release now.
