### ISSUE TITLE
Fix vitest peerDependency

### ISSUE THREAD

**Issue by Kamahl19** [chaance/vitest-dom#5]
The current setting
```
"peerDependencies": {
   "vitest": "^0.31.0"
}
```
does not allow upgrading to vitest 0.32 .

You can test this here https://semver.npmjs.com/ . `^0.31.0` will not list 0.32

**Comment by mzumberi** [comment]
Hi, i'm experiencing the same issue, i can't upgrade vitest to 0.32.2
any updates?

**Comment by buckett** [comment]
@chaance Any chance of a release with this fix in it?

**Comment by buckett** [comment]
For those using a recent version of nodejs (16+) then you can add this to your package.json:
```json
  "overrides": {
    "vitest": "^0.34.4"
  },
```
Just ensure the version matches what's in your `devDependencies`.
